[package]
name = "tetrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bevy_utils = "0.8.1"
lazy_static = "1.4.0"
rand = "0.8.5"
bevy-inspector-egui="0.12.1"
